---
role:
  os: archlinux
  pkg:
    - alsa-utils # gnome-alsamixer / pavucontrol (PulseAudio)
    - compton # composite manager
    - feh # background manager & image viewer
    - i3-wm # window manager
    - i3blocks
    - i3status
    # - libnotify
    - lxappearance # gnome-themes-standard / gtk3
    - rofi # window switcher
    - scrot # screenshot utility
    - thunar # file explorer (vifm)
    # - ttf-droid
    - otf-font-awesome # ttf has no space char
    - ttf-dejavu
    - ttf-hack
    - ttf-roboto
    - xautolock # -time 10 -locker slock
    - xclip
    # - xsel
    - name: xorg-xinit
      action: install
    - name: xorg-server
      action: install
    # - xorg-server-utils
    - qt4

    # - name: i3blocks
    #   type: yaourt
    - name: i3cat-git
      type: yaourt
      # provides: i3cat
    - name: i3lock-color
      type: yaourt
      # provides: i3lock
    - name: system-san-francisco-font-git
      type: yaourt
    # - name: arc-{firefox,icon,gtk}-theme
    #   type: yaourt
  # cp /etc/X11/xinit/xinitrc ~/.xinitrc
  # localectl set-keymap fr --no-convert
  # localectl set-x11-keymap fr macintosh
  dir:
    - .Xresources.d
    - .config/i3
  link:
    - ".Xresources"
    - ".Xresources.d/*:.Xresources.d"
    - ".config/*.conf:.config"
    - ".config/i3/*:.config/i3"
    - ".wallpaper"
