---
role:
  pkg:
    - alsa-utils # gnome-alsamixer / pavucontrol (PulseAudio)
    - compton # composite manager
    - feh # background manager & image viewer
    - i3 # window manager
    # - libnotify
    - lxappearance # gnome-themes-standard / gtk3
    - rofi # window switcher
    - scrot # screenshot utility
    - thunar # file explorer (vifm)
    # - ttf-droid
    - ttf-hack
    - xautolock # -time 10 -locker slock
    - xclip
    # - xsel
    - xorg-xinit
    - xorg-server
    # - xorg-server-utils
    - qt4
  # cp /etc/X11/xinit/xinitrc ~/.xinitrc
  link:
    - "bin:.config/i3/bin"
    - "config:.config/i3"
    - "*.conf:.config/i3"
    - ".Xresources.d:.Xresources.d"
    - ".wallpaper:.wallpaper"
