---
role:
  pkg:
    - alsa-utils # gnome-alsamixer / pavucontrol (PulseAudio)
    - compton # composite manager
    - feh # background manager & image viewer
    - i3-wm # window manager
    - i3blocks
    - i3status
    # - libnotify
    - lxappearance # gnome-themes-standard / gtk3
    - rofi # window switcher
    - scrot # screenshot utility
    - thunar # file explorer (vifm)
    # - ttf-droid
    - ttf-font-awesome
    - ttf-hack
    - ttf-roboto
    - xautolock # -time 10 -locker slock
    - xclip
    # - xsel
    - xorg-xinit
    - xorg-server
    # - xorg-server-utils
    - qt4
  # pkg_arch: # yaourt
  #   - i3cat-git # Requires go
  #   # - i3lock-color # Conflicts with i3lock
  #   - i3blocks # Not available on ARM
  #   # - system-san-francisco-font-git
  install:
    - "hash i3cat 2>/dev/null || yaourt -S --noconfirm i3cat-git"
  remove:
    - "hash i3cat 2>/dev/null && yaourt -R --noconfirm i3cat-git"
  # cp /etc/X11/xinit/xinitrc ~/.xinitrc
  link:
    - ".config/i3/*:.config/i3"
    - ".Xresources"
    - ".Xresources.d/*:.Xresources.d"
    - ".wallpaper"
